name: Build IPA
on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "Swiftgram"
        required: true
        type: choice
        options:
          - Telegram
          - Nicegram
          - Swiftgram
          - Turrit
          - Vartagram

      bundle_id:
        description: "Bundle ID"
        default: "app.swiftgram.ios"
        required: true
        type: choice
        options:
          - ph.telegra.Telegraph
          - app.nicegram
          - app.swiftgram.ios
          - com.seastar.turrit
          - org.cpartisans.vartagram

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Hide Sensitive Inputs
        uses: levibostian/action-hide-sensitive-inputs@v1
        with:
          exclude_inputs: bundle_id,display_name

      - name: Download and Validate IPA
        run: |
          wget "${{ inputs.ipa_url }}" --quiet --no-verbose -O telegram.ipa
          file_type=$(file --mime-type -b telegram.ipa)
          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The downloaded file is not a valid IPA. Detected type: $file_type."
            exit 1
          fi

      - name: Get App Version
        run: |
          unzip -q telegram.ipa -d tgextracted
          APP_NAME=$(ls tgextracted/Payload/)
          echo "APP_VERSION=$(grep -A 1 '<key>CFBundleShortVersionString</key>' "tgextracted/Payload/$APP_NAME/Info.plist" | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          rm -rf tgextracted

      - name: Get Lead Version
        run: |
          DEB_FILE=$(ls resources/com.w3ltyyy.lead_*.deb)
          echo "LEAD_VERSION=$(echo $DEB_FILE | sed 's/.*lead_\([^_]*\).*/\1/')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH Environment Variables
        run: |
          echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Cache Theos
        id: theos_cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: theos-${{ runner.os }}

      - name: Install Theos
        if: steps.theos_cache.outputs.cache-hit != 'true'
        run: |
          git clone --quiet --recursive https://github.com/theos/theos.git $THEOS

      - name: Download iOS SDK
        if: steps.theos_cache.outputs.cache-hit != 'true'
        run: |
          git clone --quiet --depth=1 -n --filter=tree:0 https://github.com/Tonwalter888/iOS-SDKs.git
          cd iOS-SDKs
          git sparse-checkout set --no-cone iPhoneOS18.6.sdk
          git checkout
          mv *.sdk $THEOS/sdks

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Clone and Build zxPluginsInject
        run: |
          git clone --quiet --depth=1 --recurse-submodules https://github.com/royerlraph79/zxPluginsInject.git
          cd zxPluginsInject && make FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless TARGET=iphone:clang:18.6:15.0
          mv .theos/obj/*.dylib ${{ github.workspace }}/zxPluginsInject.dylib

      - name: Inject Into IPA
        run: |
          tweaks="resources/com.w3ltyyy.lead_*.deb zxPluginsInject.dylib"
          if [ "${{ inputs.bundle_id }}" = "app.swiftgram.ios" ]; then
            tweaks="$tweaks resources/SwiftgramCrack.dylib"
          fi
          cyan -i telegram.ipa -o ${{ inputs.display_name }}_${{ env.APP_VERSION }}_${{ env.LEAD_VERSION }}.ipa \
            -f $tweaks \
            -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}

      - name: Create a Release
        uses: softprops/action-gh-release@v2.6.2
        with:
          tag_name: tg-ipa${{ github.run_number }}
          name: ${{ inputs.display_name }}_${{ env.APP_VERSION }}_${{ env.LEAD_VERSION }} (${{ github.run_number }})
          files: ${{ inputs.display_name }}_${{ env.APP_VERSION }}_${{ env.LEAD_VERSION }}.ipa
          draft: false

      - name: Job Summary - Build Complete
        run: echo -e '### 🛠️ Build IPA Complete!' >> $GITHUB_STEP_SUMMARY

      - name: Job Summary - Output the Draft Release Link
        run: |
          echo -e "### 🚀 Draft Release\n\nDraft release has been created successfully! You can view your release here: https://github.com/${{ github.repository }}/releases" >> $GITHUB_STEP_SUMMARY
